version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
plugins:
  markdownlint:
    enabled: true
    exclude_patterns:
      - ".github/"
  editorconfig:
    enabled: true
exclude_patterns:
  - "tests/"
  - "tests.old/"
