name: Run checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  nox:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: "ubuntu-latest"

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3.1.2
      with:
        python-version: ${{ matrix.python }}

    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox

    - name: Run pytest tests with nox
      run: nox -s "tests-${{ matrix.python }}"

    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v3.1.0
      if: ${{ matrix.python == "3.9"}}
      with:
        file: ./coverage.xml

    - name: Send coverage report to codeclimate
      uses: paambaati/codeclimate-action@v3.0.0
      if: ${{ matrix.python == "3.9"}}
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
