name: "Documentation build check"
on:
  pull_request:
    branches:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.9"

      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: Build docs with nox
        run: nox -s docs

      - uses: actions/upload-artifact@v3.0.0
        with:
          name: DocumentationHTML
          path: docs/build/html/
